# Generated by Django 3.2.16 on 2022-12-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True, unique=True)),
                ('gst_number', models.CharField(max_length=15, null=True, unique=True)),
                ('aadhar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('pan_no', models.CharField(max_length=10, null=True, unique=True)),
                ('enabled', models.BooleanField()),
                ('gst_verified', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mi_orgs',
            },
        ),
    ]
