# Generated by Django 3.2.16 on 2022-12-18 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgs',
            old_name='email',
            new_name='company_email',
        ),
        migrations.AddField(
            model_name='orgs',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orgs',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgs',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='OrgPartners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgs')),
            ],
            options={
                'db_table': 'mi_org_partners',
            },
        ),
        migrations.CreateModel(
            name='OrgBranches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_address', models.TextField(null=True)),
                ('identification_id', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgs')),
            ],
            options={
                'db_table': 'mi_org_branches',
            },
        ),
    ]
