# Generated by Django 4.1.4 on 2023-01-04 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20221218_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='registered_company_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='company_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 10, 34, 21, 19655)),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='gst_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 10, 34, 21, 19674)),
        ),
    ]
