# Generated by Django 4.1.4 on 2023-01-05 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_orgs_registered_company_name_alter_orgs_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 4, 49, 58, 514121)),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 4, 49, 58, 514154)),
        ),
    ]
