# Generated by Django 4.1.5 on 2023-01-10 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_orgs_created_at_alter_orgs_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgs',
            old_name='company_name',
            new_name='company_address',
        ),
        migrations.AlterField(
            model_name='orgs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 4, 26, 58, 375221)),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 4, 26, 58, 375244)),
        ),
    ]
