# Generated by Django 4.1.5 on 2023-01-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_rename_company_name_orgs_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
