# Generated by Django 4.1.5 on 2023-01-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_orgs_created_at_alter_orgs_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='cin_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orgs',
            name='company_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orgs',
            name='tan_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
