# Generated by Django 4.1.5 on 2023-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_orgs_cin_no_orgs_company_id_orgs_tan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='gst_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='pan_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
