# Generated by Django 3.2.16 on 2023-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_alter_orgs_gst_number_alter_orgs_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='logo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
