# Generated by Django 4.2.4 on 2023-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_orgs_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='company_website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
