# Generated by Django 4.2.4 on 2023-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_orgs_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='gst_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='registered_company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
