# Generated by Django 5.0 on 2024-01-25 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_alter_orgs_gst_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbranches',
            name='pan_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orgbranches',
            name='tan_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orgbranches',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
