# Generated by Django 5.0 on 2024-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_orgbranches_pan_no_orgbranches_tan_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbranches',
            name='branch_name',
            field=models.TextField(null=True),
        ),
    ]
