# Generated by Django 3.2.16 on 2022-12-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('hsn_code', models.TextField(null=True)),
                ('meta', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mi_products',
            },
        ),
    ]
