# Generated by Django 4.1.5 on 2023-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
