# Generated by Django 4.1.5 on 2023-01-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_code',
            field=models.TextField(null=True),
        ),
    ]
