# Generated by Django 3.2.16 on 2022-12-18 07:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(null=True)),
                ('application_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgs')),
            ],
            options={
                'db_table': 'mi_applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('certificate_number', models.CharField(max_length=100, null=True)),
                ('validity_number', models.CharField(max_length=100, null=True)),
                ('state_of_issue', models.CharField(max_length=100, null=True)),
                ('pricing', models.JSONField()),
                ('composition', models.JSONField()),
                ('attachment_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=[], size=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applications')),
            ],
            options={
                'db_table': 'mi_application_details',
            },
        ),
    ]
