# Generated by Django 3.2.16 on 2022-12-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
    ]
