# Generated by Django 4.1.4 on 2022-12-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orgs', '0002_auto_20221218_0859'),
        ('applications', '0002_applications_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='applicationdetails',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='applicationdetails',
            name='state_of_issue',
        ),
        migrations.RemoveField(
            model_name='applicationdetails',
            name='validity_number',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='compositions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='declaration',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='is_imported',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='is_product_regulated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='product_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='regulated_product_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='sm_process',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='unregulated_product_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='unique_application_id',
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='pricing',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='ApplicationItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_id', models.CharField(max_length=100)),
                ('item_details', models.JSONField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applications')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.orgbranches')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'mi_application_items',
                'unique_together': {('application_id', 'sequence_id', 'product_id')},
            },
        ),
    ]
