# Generated by Django 4.1.4 on 2023-01-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_orgs_created_at_alter_orgs_updated_at'),
        ('applications', '0003_remove_applicationdetails_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitems',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgbranches'),
        ),
    ]
