# Generated by Django 4.1.5 on 2023-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applicationitems_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='label_criteria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='melted_criteria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
