# Generated by Django 4.1.5 on 2023-01-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationdetails_label_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeedbacks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_application_id', models.CharField(max_length=100)),
                ('sequence_id', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mi_application_feedbacks',
            },
        ),
    ]
