# Generated by Django 4.1.5 on 2023-01-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationfeedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfeedbacks',
            name='external_application_id',
        ),
        migrations.RemoveField(
            model_name='applicationfeedbacks',
            name='sequence_id',
        ),
        migrations.AddField(
            model_name='applicationfeedbacks',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.applications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationfeedbacks',
            name='application_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.applicationitems'),
            preserve_default=False,
        ),
    ]
