# Generated by Django 4.1.5 on 2023-01-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_applicationfeedbacks_external_application_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfeedbacks',
            name='application',
        ),
    ]
