# Generated by Django 4.1.5 on 2023-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_applicationfeedbacks_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitems',
            name='item_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
