# Generated by Django 4.1.5 on 2023-02-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationitems_item_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationitems',
            unique_together=set(),
        ),
    ]
