# Generated by Django 4.1.5 on 2023-02-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_name'),
        ('applications', '0010_alter_applicationitems_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationitems',
            unique_together={('application', 'product', 'sequence_id', 'item_key')},
        ),
    ]
