# Generated by Django 4.1.5 on 2023-02-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_applicationitems_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='value_addition',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
