# Generated by Django 4.1.6 on 2023-05-18 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_applicationdetails_value_addition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdetails",
            name="attachment_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
