# Generated by Django 4.1.6 on 2023-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_alter_applicationdetails_attachment_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdetails",
            name="attachments",
            field=models.JSONField(null=True),
        ),
    ]
