# Generated by Django 4.2.4 on 2023-09-25 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0017_alter_applicationreview_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
