# Generated by Django 4.2.4 on 2023-10-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_applicationreview_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsupervisor',
            old_name='assignee',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='applicationsupervisor',
            old_name='supervisor',
            new_name='reviewer',
        ),
        migrations.AlterModelTable(
            name='applicationsupervisor',
            table='mi_applications_reviewer',
        ),
    ]
