# Generated by Django 4.2.4 on 2023-10-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_rename_assignee_applicationsupervisor_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='application_doc',
            field=models.CharField(null=True),
        ),
    ]
