# Generated by Django 4.1.4 on 2022-12-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verify_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, null=True)),
                ('verification_code', models.CharField(max_length=200, null=True)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'db_table': 'mi_verify_user',
            },
        ),
    ]
