# Generated by Django 4.2.3 on 2023-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_user',
            name='count',
            field=models.IntegerField(default=5),
        ),
    ]
