# Generated by Django 4.2.7 on 2023-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0002_verify_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_user',
            name='resend_flag',
            field=models.BooleanField(default=True),
        ),
    ]
