# Generated by Django 4.2.7 on 2023-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('company_name', models.CharField()),
                ('company_email', models.CharField()),
                ('message', models.CharField()),
                ('country', models.CharField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mi_contactus',
            },
        ),
    ]
